# Does the file ex1 exist already?
# No. Ok, is there another file that starts with ex1?
# Yes, it's called ex1.c. Do I know how to build .c files?
# Yes, I run this command cc ex1.c   -o ex1 to build them.
# I shall make you one ex1 by using cc to build it from ex1.c.

# -Wall enables all warnings (not really all warnings)
CFLAGS=-Wall -g

clean:
	rm -f ex1
